version: "2"

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        environment:
            - INFLUXDB_ADMIN_ENABLED=true
        ports:
            - "8083:8083"
            - "8086:8086"
        env_file:
            - 'env.influxdb'
        volumes:
            - ./data/influxdb:/var/lib/influxdb

    backend:
        image: aospan/antminer-monitor-backend
        environment:
            - MINER_HOST=192.168.1.99
            - MINER_DB_HOST=influxdb
        restart: always
        links:
            - influxdb

    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        ports:
            - "3000:3000"
        env_file:
            - 'env.grafana'
        links:
            - influxdb
